name: Create release
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Latest release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        path: releases/'
        filename: 'skinCore-latest.zip'
        directory: 'releases'
        exclusions: '*.git* /*scss/* /*releases/* .editorconfig .gitignore LICENSE README.md .gitkeep'